version: "3.9"

services:
  web:
    build: . # Build the Dockerfile in the current directory
    ports:
      - "8080:8080"
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code # Replicate local changes to the container
